### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by captn3m0** [captn3m0/muzi-android#1]
**Version 1**
- [x] Search should be functional
- [x] Browsing should be functional on the basis of artists/albums
- [x] Language Filter
- [x] Top Tracks, Albums (for this week)
- [ ] Recently added albums
- [ ] Integration with the Android Music System

**Other Basic Features**
- [x] Shuffle, Repeat, Volume
- [ ] Now Playing screen (with Album Art)
- [ ] Intranet Detection (Muzi should complain when it cannot reach sdslabs servers)
- [x] Feedback Link

**Version 2**
- [ ] Tickr should be visible and available
- [ ] Full Screen display of artist art
- [ ] Lyrics
- [ ] Request a Song
- [x] Support major tablets (Nexus/Galaxy Tab at least)

**Version 3**
- [ ] Login (using the new OAuth API)
- [ ] Like a Track
- [ ] User's Playlists (creation/deletion/browsing) only after Login
- [ ] Playlist changes (addition, removal)
- [ ] Slow connection mode
